# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/29360/Desktop/ECE385/Tetris_final/Tetris/tetris_hardware/Tetris.srcs/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0.xci
# IP: The module: 'mb_block_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/29360/Desktop/ECE385/Tetris_final/Tetris/tetris_hardware/Tetris.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/29360/Desktop/ECE385/Tetris_final/Tetris/tetris_hardware/Tetris.srcs/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0.xci
# IP: The module: 'mb_block_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/29360/Desktop/ECE385/Tetris_final/Tetris/tetris_hardware/Tetris.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
